services:
  catalogue:
    build:
      context: ./CATALOGUE
      dockerfile: Dockerfile
    image: basha831750/catalogue:v1
    # container_name: catalogue
    # I have commented this lines to build only images 
    depends_on:
    - mongodb
  mongodb:
    build:
      context: ./MONGODB
      dockerfile: Dockerfile
    image: basha831750/mongodb:v1
    # container_name: mongodb 
    volumes:
      - mongodb:/data/db 

  cart:
    build:
      context: ./CART
      dockerfile: Dockerfile
    image: basha831750/cart:v1
    # container_name: cart   
    depends_on:
    - catalogue
    - redis
  redis:
   image: basha831750/redis:7
  #  container_name: redis 
   volumes:
     - redis:/data

  mysql:
    build:
      context: ./MYSQL
      dockerfile: Dockerfile
    image: basha831750/mysql:v1
    # container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  payment:
    build:
      context: ./PAYMENT
      dockerfile: Dockerfile
    image: basha831750/payment:v1
    # container_name: payment
    depends_on:
    - cart
    - user
    - rabbitmq

  user:
    build:
      context: ./USER
      dockerfile: Dockerfile
    image: basha831750/user:v1
    # container_name: user
    depends_on:
    - redis
    - mongodb

  rabbitmq:
    image: basha831750/rabbitmq:3
    # container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  shipping:
    build:
      context: ./SHIPPING
      dockerfile: Dockerfile
    image: basha831750/shipping:v1
    # container_name: shipping
    depends_on:
    - cart
    - mysql

  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    image: basha831750/frontend:v1
    # container_name: frontend
    ports:
      - "80:80"
    depends_on:
    - cart
    - catalogue
    - shipping
    - payment
    - user
           

networks:
  default:
    driver: bridge
    name: roboshop
    external: false   

volumes:
  mongodb:
  mysql:
  redis:
  rabbitmq: 
