

services:
  cart:
    build:
      context: /cart
      dockerfile: Dockerfile
    image: cart:v1
    container_name: cart

  catalogue:
    build:
      context: /catalogue
      dockerfile: Dockerfile
    image: catalogue:v1
    container_name: catalogue

  frontend:
    build:
      context: /frontend
      dockerfile: Dockerfile
    image: frontend:v1
    container_name: frontend
  mysql:
    build:
      context: /mysql
      dockerfile: Dockerfile
    image: mysql:v1
    container_name: mysql

  payment:
    build:
      context: /payment
      dockerfile: Dockerfile
    image: payment:v1
    container_name: payment

  shipping:
    build:
      context: /shipping
      dockerfile: Dockerfile
    image: shipping:v1
    container_name: shipping

  user:
    build:
      context: /user
      dockerfile: Dockerfile
    image: user:v1
    container_name: user    

    

networks:
  default:
    driver: bridge
    name: roboshop
    external: true
      