

services:
  cart:
    build:
      context: ./services/cart
      dockerfile: Dockerfile
    image: cart:v1
    container_name: cart

  catalogue:
    build:
      context: ./services/catalogue
      dockerfile: Dockerfile
    image: catalogue:v1
    container_name: catalogue

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    image: frontend:v1
    container_name: frontend
  mysql:
    build:
      context: ./services/mysql
      dockerfile: Dockerfile
    image: mysql:v1
    container_name: mysql

  payment:
    build:
      context: ./services/payment
      dockerfile: Dockerfile
    image: payment:v1
    container_name: payment

  shipping:
    build:
      context: ./services/shipping
      dockerfile: Dockerfile
    image: shipping:v1
    container_name: shipping

  user:
    build:
      context: ./services/user
      dockerfile: Dockerfile
    image: user:v1
    container_name: user    

    

networks:
  default:
    driver: bridge
    name: roboshop
    external: true
      