

services:
  shipping:
    build:
      context: .
      dockerfile: Dockerfile
    image: shipping:v1
    container_name: shipping
    depends_on:
    - cart
    - mysql
  cart:
   image: cart:v1
  mysql:
   image: mysql:v1   

networks:
  default:
    driver: bridge
    name: roboshop
    external: true
      