

services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    image: user:v1
    container_name: user
    depends_on:
    - redis
      mongodb
  mongodb:
    image: mongodb:v1
  redis:
    image: redis:v1      

networks:
  default:
    driver: bridge
    name: roboshop
    external: true
      